services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      # Aquí ajustamos a tus datos de IntelliJ
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userdev
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"

  app:
    image: biblioteca-api
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # El host "db" es obligatorio porque así se llama el servicio arriba
      - DB_URL=jdbc:mysql://db:3306/biblioteca_db
      - DB_USER=userdev
      - DB_PASSWORD=123456
