services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userdev
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: henrydev2026/biblioteca-api:latest
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/biblioteca_db
      - DB_USERNAME=userdev
      - DB_PASSWORD=123456

volumes:
  mysql_data:
